// Chapter 5

xBookUtils.terms['central limit theorem'] = '<strong>central limit theorem</strong> a statement about the shape that a sampling distribution of the mean takes if the size of the samples is large and every possible sample were obtained.';
xBookUtils.terms['confidence interval'] = '<strong>confidence interval</strong> a range within which it is estimated that a population value falls.';
xBookUtils.terms['consent rate'] = '<strong>consent rate</strong> the percentage of targeted subjects who agree to participate in a study.';
xBookUtils.terms['convenience sample'] = '<strong>convenience sample</strong> a sampling strategy in which cases are selected for study based on the ease with which they can be obtained.';
xBookUtils.terms['interval estimate'] = '<strong>interval estimate</strong> an estimate of a population value that says the population value falls somewhere within a range of values.';
xBookUtils.terms['point estimate'] = '<strong>point estimate</strong> an estimate of a population value that is a single value.';
xBookUtils.terms['random sample'] = '<strong>random sample</strong> a sampling strategy in which each case in the population has an equal chance of being selected.';
xBookUtils.terms['representative'] = '<strong>representative</strong> all the attributes of the population are present in the sample in approximately the same proportion as in the population.';
xBookUtils.terms['sampling distribution'] = '<strong>sampling distribution</strong> a frequency distribution generated by taking repeated, random samples from a population and generating some value, like a mean, for each sample.';
xBookUtils.terms['sampling error'] = '<strong>sampling error</strong> discrepancies, due to random factors, between sample statistic and a population parameter.';
xBookUtils.terms['self-selection bias'] = '<strong>self-selection bias</strong> a nonrepresentative sample that may occur when the subjects who agree to participate in a research study differ from those who choose not to participate.';
xBookUtils.terms['standard error of the mean'] = '<strong>standard error of the mean</strong> the standard deviation of a sampling distribution of the mean.';

